### ISSUE TITLE
update from 1.46 

### ISSUE THREAD

**Issue by tanvan81** [loopj/android-async-http#1133]
Hi

I use version 1.46, when I update to 1.4.9, I have some problem
`client.get(url, params, new AsyncHttpResponseHandler() {
                    @Override
                    public void onSuccess(int statusCode, Header[] headers, byte[] responseBody) {

                    }

                    @Override
                    public void onFailure(int statusCode, Header[] headers, byte[] responseBody, Throwable error) {

                    }
                });`

when I build project, android studio show error

` is not abstract and does not override abstract method onFailure(int,Header[],byte[],Throwable) in AsyncHttpResponseHandler`

I still input 
`import cz.msebera.android.httpclient.Header;`

Please, h\

**Comment by yujiaao** [comment]
you must remove` import org.apache.http.Header;`

**Comment by tanvan81** [comment]
yes, I remove import org.apache.http.Header;

but still error

**Comment by yujiaao** [comment]
change org.apache.http.XXX to cz.msebera.android.httpclient.XXX
