### ISSUE TITLE
java.lang.NoClassDefFoundError: cz.msebera.android.httpclient.util.Args

### ISSUE THREAD

**Issue by tingbob** [loopj/android-async-http#1083]
When I new AsyncHttpClient, it will list followed errors. I don't know why.
java.lang.NoClassDefFoundError: cz.msebera.android.httpclient.util.Args
                                                                           at cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory.<init>(SSLSocketFactory.java:337)
                                                                           at cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory.getSocketFactory(SSLSocketFactory.java:169)
                                                                           at com.loopj.android.http.AsyncHttpClient.getDefaultSchemeRegistry(AsyncHttpClient.java:301)
                                                                           at com.loopj.android.http.AsyncHttpClient.<init>(AsyncHttpClient.java:177)
                                                                           at com.loopj.android.http.AsyncHttpClient.<init>(AsyncHttpClient.java:147)

**Comment by tingbob** [comment]
The version is 1.4.9

**Comment by HarkDev** [comment]
Exact same problem here.
NoClassDefFoundError: cz.msebera.android.httpclient.util.Args

**Comment by mayankdtu** [comment]
Same problem arrived with android 4.4.2 but working fine with 5.0

**Comment by mohammadzzz** [comment]
I have exactly the same problem
Any solution?

**Comment by tingbob** [comment]
OK. I solve the problem. When you compile some libs may be due to multidex error especially using proguard rules, it will not recognize the right class of the lib.  Here compiling lib is included apache lib, your project may compile the apache lib in other lib repeatedly.
So you should add following code in gradle 
`android {

    ...
    defaultConfig {
        ...
        // Enabling multidex support.
        multiDexEnabled true
    }
    ...
}
dependencies {
  compile 'com.android.support:multidex:1.0.0'
}`
and add codes in your application
`@Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }`
Hope is helpless.

**Comment by ahaqxjl** [comment]
You saved me from struggling on this problem for 2 days!!!! It works! Thank you.
